stages:
- prebuild
- build
- publish

variables:
  CBC_VERSION: 2.10.3

#
# Build Stages
#
.build:  &build
  stage: build
  script: 
  # Install CBC from bintray
  - mkdir Cbc && cd Cbc && pwd
  - wget https://bintray.com/coin-or/download/download_file?file_path=$CBC_FILE -O $CBC_FILE
  - if [[ "$CBC_FILE" == *.zip ]]; then unzip $CBC_FILE; else tar -zxvf $CBC_FILE; fi
  - cd .. && pwd
  - for FILE in patches/*.diff; do patch -p1 < $FILE; done
  # Compile python module
  - /opt/python/$PYTHON_ENV/bin/python setup.py build_ext --swig="$SWIG" --swig-opts="-doxygen -c++ -I./Cbc/include/coin/" -I./Cbc/include/coin/ -L./Cbc/lib/
  # Build package
  - /opt/python/$PYTHON_ENV/bin/pip install wheel --upgrade
  - /opt/python/$PYTHON_ENV/bin/python setup.py bdist_wheel
  # Test the packages
  - /opt/python/$PYTHON_ENV/bin/pip install dist/*.whl
  - LD_LIBRARY_PATH=./Cbc/lib/ /opt/python/$PYTHON_ENV/bin/python -m cbcpy
  artifacts:
    paths:
    - dist

.buildlinux:  &buildlinux
  <<: *build
  image: quay.io/pypa/manylinux2010_x86_64
  stage: build
  variables:
    CBC_FILE: Cbc-$CBC_VERSION-linux-x86_64-gcc4.8.tgz
    SWIG: /usr/local/bin/swig
  before_script:
  # Insall dependencies
  - yum install -y wget pcre-devel
  # Install SWIG
  - wget --no-check-certificate https://sourceforge.net/projects/swig/files/swig/swig-4.0.0/swig-4.0.0.tar.gz
  - tar -zxvf swig-4.0.0.tar.gz
  - cd swig-4.0.0
  - ./configure && make && make install
  - cd ..

.buildwin:  &buildwin
  <<: *build
  variables:
    SWIG: swigwin-4.0.0/swig.exe
    CBC_FILE: Cbc-$CBC_VERSION-win32-msvc9.zip
  before_script: 
  # Install SWIG
  - wget https://sourceforge.net/projects/swig/files/swigwin/swigwin-4.0.0/swigwin-4.0.0.zip
  - unzip swigwin-4.0.0.zip
    
build_cp27-cp27m_x86_64_linux:
  <<: *buildlinux
  variables:
    PYTHON_ENV: cp27-cp27m
    
build_cp27-cp27mu_x86_64_linux: 
  <<: *buildlinux
  variables:
    PYTHON_ENV: cp27-cp27mu

build_cp34-cp34m_x86_64_linux: 
  <<: *buildlinux
  variables:
    PYTHON_ENV: cp34-cp34m
    
build_cp35-cp35m_x86_64_linux: 
  <<: *buildlinux
  variables:
    PYTHON_ENV: cp35-cp35m

build_cp36-cp36m_x86_64_linux: 
  <<: *buildlinux
  variables:
    PYTHON_ENV: cp36-cp36m
    
build_cp37-cp37m_x86_64_linux: 
  <<: *buildlinux
  variables:
    PYTHON_ENV: cp37-cp37m

build_py27_win32_msvc9: 
  <<: *buildwin
  image: ikus060/docker-python:2.7-vc2008express
  
#
# Publish manylinux packages
#

publish_nexus:
  stage: publish
  image: python:3
  script:
  - apt update && apt install -y patchelf
  - pip install twine auditwheel --upgrade
  - python setup.py sdist
  - for FILE in dist/*.whl; do auditwheel repair $FILE; done
  - twine upload dist/* -u $NEXUS_USR -p $NEXUS_PWD --repository-url $NEXUS_PYPI_URL

publish_pypi:
  stage: publish
  image: python:3
  only:
  - tags
  script:
  - apt update && apt install -y patchelf
  - pip3 install twine --upgrade
  - python setup.py sdist
  - for FILE in dist/*.whl; do auditwheel repair $FILE; done
  - twine upload dist/* -u $PYPI_USR -p $PYPI_PWD
  