stages:
- prebuild
- build
- publish

#  CBCURL: https://github.com/ikus060/Cbc
#  COINBREWURL: https://raw.githubusercontent.com/coin-or/coinbrew/42bc4ddd6698c7cd6a154147852522f2e061d1c7/coinbrew

# TODO We should probably fix the version and not use master HERE.

#
# Build Stages.
#

.build:  &build
  stage: build
  script: 
  # Install CBC
  - mkdir Cbc && cd Cbc && pwd
  - wget https://bintray.com/coin-or/download/download_file?file_path=$CBC_FILE -O $CBC_FILE
  - if [[ "$CBC_FILE" == *.zip ]]; then unzip $CBC_FILE; else tar -zxvf $CBC_FILE; fi
  - cd .. && pwd
  - for FILE in patches/*.diff; do patch -p1 < $FILE; done
  # Compile python module
  - python setup.py build_ext --swig="$SWIG" --swig-opts="-c++ -I./Cbc/include/coin/" -I./Cbc/include/coin/ -L./Cbc/lib/
  # Build package
  - python -m pip install wheel --upgrade
  - python setup.py bdist_wheel
  # Test the packages
  - pip install dist/*.whl
  - python -m cbcpy
  artifacts:
    paths:
    - dist

.buildlinux:  &buildlinux
  variables:
    CBC_FILE: Cbc-2.10.3-linux-x86_64-gcc4.8.tgz
    SWIG: /usr/local/bin/swig
  before_script: 
  # Install SWIG
  - wget https://sourceforge.net/projects/swig/files/swig/swig-4.0.0/swig-4.0.0.tar.gz
  - tar -zxvf swig-4.0.0.tar.gz
  - cd swig-4.0.0
  - ./configure && make && make install
  - cd ..
    
.buildwin:  &buildwin
  variables:
    SWIG: swigwin-4.0.0/swig.exe
    CBC_FILE: Cbc-2.10.3-win32-msvc9.zip
  before_script: 
  # Install SWIG
  - wget https://sourceforge.net/projects/swig/files/swigwin/swigwin-4.0.0/swigwin-4.0.0.zip
  - unzip swigwin-4.0.0.zip
    
build_py2_x86_64_linux:
  <<: *buildlinux
  image: python:2
    
build_py35_x86_64_linux: 
  <<: *buildlinux
  image: python:3.5

build_py36_x86_64_linux: 
  <<: *buildlinux
  image: python:3.6
    
build_py37_x86_64_linux: 
  <<: *buildlinux
  image: python:3.7
    
# TODO ikus060/docker-wine-py2-py3 should be replaced to use a specific python version.
build_py2_win32_msvc9: 
  <<: *buildwin
  image: ikus060/docker-wine-py2-py3
  
#
# Publish
#

publish_nexus:
  stage: publish
  image: python:3
  script:
  - pip install twine --upgrade
  - python setup.py sdist
  - twine upload dist/* -u $NEXUS_USR -p $NEXUS_PWD --repository-url $NEXUS_PYPI_URL

publish_pypi:
  stage: publish
  image: python:3
  only:
  - tags
  script:
  - pip3 install twine --upgrade
  - python setup.py sdist
  - twine upload dist/* -u $PYPI_USR -p $PYPI_PWD
  