image: $DOCKER_REGISTRY/pdsl/cbcpy-build:$CI_PIPELINE_IID

stages:
- prebuild
- build
- publish

variables:
  CBCURL: https://github.com/ikus060/Cbc

# TODO We should probably fix the version and not use master HERE.

# Create a Docker images with SWIG
prebuild-docker-image:
  image: docker:stable
  stage: prebuild
  script:
  - docker login $DOCKER_REGISTRY -u $DOCKER_USR -p $DOCKER_PWD
  - docker build -t cbcpy-build .
  - docker tag cbcpy-build $DOCKER_REGISTRY/pdsl/cbcpy-build:$CI_PIPELINE_IID
  - docker push $DOCKER_REGISTRY/pdsl/cbcpy-build:$CI_PIPELINE_IID

.build:  &build
  stage: build
  before_script:
  # Install & Compile CBC
  - wget https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew
  - bash ./coinbrew fetch $CBCURL --no-prompt --no-third-party
  - bash ./coinbrew build Cbc --no-prompt --parallel-jobs=`nproc` --disable-shared --with-pic --target=$TARGET --host=$TARGET
  script:
  - $PYTHON setup.py build_ext --swig-opts="-c++ -I./build/include/coin/" -I./build/include/coin/ -L./build/lib/
  artifacts:
    paths:
    - build

build_py2:
  <<: *build
  variables:
    TARGET: x86_64-linux-gnu
    PYTHON: python2

build_py3:
  <<: *build
  variables:
    TARGET: x86_64-linux-gnu
    PYTHON: python2
    
.publish:  &publish
  stage: publish
  script:
  - $PYTHON -m pip install wheel twine --upgrade
  - $PYTHON setup.py bdist_wheel
  - twine upload dist/* -u $NEXUS_USR -p $NEXUS_PWD --repository-url $NEXUS_PYPI_URL

publish_nexus_py2:
  <<: *publish
  stage: publish
  variables:
    PYTHON: python2
  dependencies:
  - build_py2

publish_nexus_py3:
  <<: *publish
  stage: publish
  variables:
    PYTHON: python3
  dependencies:
  - build_py3
  
.publish_pypi:  &publish_pypi
  stage: publish
  only:
  - tags
  script:
  - $PYTHON -m pip install wheel twine --upgrade
  - $PYTHON setup.py bdist_wheel
  - twine upload dist/* -u $PYPI_USR -p $PYPI_PWD

publish_pypi_py2:
  <<: *publish_pypi
  stage: publish
  variables:
    PYTHON: python2
  dependencies:
  - build_py2
  
publish_pypi_py3:
  <<: *publish_pypi
  stage: publish
  variables:
    PYTHON: python3
  dependencies:
  - build_py3
