stages:
- prebuild
- build
- publish

variables:
  CBCURL: https://github.com/ikus060/Cbc
  COINBREWURL: https://raw.githubusercontent.com/coin-or/coinbrew/42bc4ddd6698c7cd6a154147852522f2e061d1c7/coinbrew

# TODO We should probably fix the version and not use master HERE.

#
# Build Stages.
#

.build:  &build
  stage: build
  script: 
  # Install SWIG
  - wget https://sourceforge.net/projects/swig/files/swig/swig-4.0.0/swig-4.0.0.tar.gz
  - tar -zxvf swig-4.0.0.tar.gz
  - cd swig-4.0.0
  - ./configure && make && make install
  # Install & Compile CBC
  - wget $COINBREWURL
  - bash ./coinbrew fetch $CBCURL --no-prompt --no-third-party
  - bash ./coinbrew build Cbc --no-prompt --disable-shared --with-pic --target=$TARGET --host=$TARGET
  # Compile python module
  - python setup.py build_ext --swig-opts="-c++ -I./build/include/coin/" -I./build/include/coin/ -L./build/lib/
  # Build package
  - python -m pip install wheel --upgrade
  - python setup.py bdist_wheel
  artifacts:
    paths:
    - dist

build_py2_x86_64_linux:
  <<: *build
  image: python:2
  variables:
    TARGET: x86_64-linux-gnu
  before_script:
  - apt update && apt install -y gfortran
    
build_py35_linux64:
  <<: *build
  image: python:3.5
  variables:
    TARGET: x86_64-linux-gnu
  before_script:
  - apt update && apt install -y gfortran

build_py36_linux64:
  <<: *build
  image: python:3.6
  variables:
    TARGET: x86_64-linux-gnu
  before_script:
  - apt update && apt install -y gfortran
    
build_py37_linux64:
  <<: *build
  image: python:3.7
  variables:
    TARGET: x86_64-linux-gnu
  before_script:
  - apt update && apt install -y gfortran
    
build_py2_win32:
  <<: *build
  variables:
    CXXFLAGS: -D__MINGW64__
    LDFLAGS: -static-libgcc -static-libstdc++
    TARGET: i686-w64-mingw32
    PYTHON: python:2
  before_script:
  - apt update && apt install -y gcc-mingw-w64 mingw-w64 g++-multilib
  allow_failure: true

build_py35_win32:
  <<: *build
  variables:
    CXXFLAGS: -D__MINGW64__
    LDFLAGS: -static-libgcc -static-libstdc++
    TARGET: i686-w64-mingw32
    PYTHON: python:3.5
  before_script:
  - apt update && apt install -y gcc-mingw-w64 mingw-w64 g++-multilib
  allow_failure: true
    
build_py2_win64:
  <<: *build
  variables:
    LDFLAGS: -static-libgcc -static-libstdc++
    TARGET: x86_64-w64-mingw32
    PYTHON: python:2
  before_script:
  - apt update && apt install -y gcc-mingw-w64 mingw-w64 g++-multilib
  allow_failure: true

build_py35_win64:
  <<: *build
  variables:
    LDFLAGS: -static-libgcc -static-libstdc++
    TARGET: x86_64-w64-mingw32
    PYTHON: python:3.5
  before_script:
  - apt update && apt install -y gcc-mingw-w64 mingw-w64 g++-multilib
  allow_failure: true

#
# Publish
#

publish_nexus_py2:
  stage: publish
  script:
  - pip3 install twine --upgrade
  - twine upload dist/* -u $NEXUS_USR -p $NEXUS_PWD --repository-url $NEXUS_PYPI_URL

publish_pypi:
  stage: publish
  only:
  - tags
  script:
  - pip3 install twine --upgrade
  - twine upload dist/* -u $PYPI_USR -p $PYPI_PWD
  